# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f9db97a38a525aa0532df3dabdb9993398fbf4ce7005f45e061b4959e5b036f88e4d6982badb3325ec2f2befbad3b3b33a16c69312f14b66c52117ff2b54397

test:
  secret_key_base: 402bd64df51bf297105e98e7fc910e3286009ed50da437728ea05cd4b53addc22558d17e9882bac6b8cd18af1394a8e88d90a1f999ea2f9b48833521f5bed8b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
